'use strict';

module.exports = {
  ActionTypes: {
    GET_USERS: "GET_USERS",
    GET_USER : "GET_USER",
    GET_HOSTS : "GET_HOSTS",
    GET_HOST : "GET_HOST",
    GET_MEALS : "GET_MEALS",
    GET_MEAL : "GET_MEAL",
    GET_ORDERS : "GET_ORDERS",
    GET_ORDER : "GET_ORDER",
    GET_DISHES : "GET_DISHES",
    GET_DISH : "GET_DISH",
    GET_TRANSACTIONS : "GET_TRANSACTIONS",
    GET_TRANSACTION : "GET_TRANSACTION",
    GET_JOBS : "GET_JOBS",
    GET_JOB : "GET_JOB",
    GET_CHECKLISTS : "GET_CHECKLISTS",
    GET_CHECKLIST : "GET_CHECKLIST",
    GET_COUPON : "GET_COUPON",
    GET_COUPONS : "GET_COUPONS",
    GET_REVIEW : "GET_REVIEW",
    GET_REVIEWS : "GET_REVIEWS",
    CREATE_VIEW : "CREATE_VIEW",
    TAB_CHANGE : "TAB_CHANGE",
    SEARCH_CHANGE : "SEARCH_CHANGE",
    MODEL_CREATE : "MODEL_CREATE",
    NO_RESULT : "NO_RESULT",
    BAD_REQUEST : "BAD_REQUEST"
  }
};
