version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-app

#permissions:
#- object: /
#   pattern: "**"
#   owner: ec2-user
#   group: ec2-user
#
hooks:
  BeforeInstall:
    - location: bin/exportENV.sh
      timeout: 300
  AfterInstall:
    - location: bin/install.sh
      timeout : 10000
